# Analise - Final

## Revisões e Erros

1.  Deflacionar indicadores - Aplicar função de deflação 
2.  Regiões  
    2.1. Repetidas - Caucaia e Sobral 
    2.2. Inexistente - Cariri e Farias Brito 
3. Recalcular a indices per capita - somando população do da região 
4. IDH - Repetidas - Baixo

## Biblioteca

In [1]:
# Biblioteca 
import pandas as pd 
import numpy as np 
import json
from database import * 
import datetime
import plotly.express as px

## Função de deflação

In [2]:
def deflação(serie,ano_base):
    IPCA = {'1980':99.2504889542286,'1981':95.6230442372937,'1982':104.790433277431,'1983':164.01202400196,'1984':215.263325738616,'1985':242.229795207366,'1986':79.6644968645082,'1987':363.411523705732,'1988':980.213487131888,'1989':1972.91162333472,'1990':1620.96646812495,'1991':472.6999999996,'1992':1119.10075082943,'1993':2477.14712129698,'1994':916.46,'1995':22.4081616590914,'1996':9.56495181758998,'1997':5.22431853525425,'1998':1.65497817994227,'1999':8.93978878068851,'2000':5.97459334239816,'2001':7.67343641407332,'2002':12.5302733566877,'2003':9.30051280040003,'2004':7.59949584882642,'2005':5.68922681873509,'2006':3.14151613157687,'2007':4.45765855337372,'2008':5.90272439065465,'2009':4.31165006256784,'2010':5.90868872179453,'2011':6.50335274368017,'2012':5.83859471814745,'2013':5.91068325533108,'2014':6.40747079590815,'2015':10.6730281339751,'2016':6.28798821322138,'2017':2.94742132043471,'2018':3.74558117019155,'2019':4.30615161715953,'2020':4.51745688642451}
    deflac =[]
    for i in range(0,len(serie)):
        ano = serie.iloc[i]['ano']
        x = (IPCA[str(ano)]/IPCA[str(2019)])*serie.loc[i]['Receitas_realizadas_Bimestre']
        deflac.append(x)
        
    return(deflac)

## Função de Series Temporais

In [3]:
def time_serie(dataframe):
    new_serie=[]
    for i in dataframe:
        new_serie.append(datetime.datetime.strptime(str(i),'%Y'))
        
    return new_serie

In [4]:
# dados = ReceitasAdicionais.select(ReceitasAdicionais.municipio, ClassificaçõesMunicipio.Região, ClassificaçõesMunicipio.IDH,ReceitasAdicionais.codigo_Municipio, ReceitasAdicionais.estado, ReceitasAdicionais.ano, ReceitasAdicionais.campo, ReceitasAdicionais.Receitas_realizadas_Bimestre,(ReceitasAdicionais.Receitas_realizadas_Bimestre/Populacao.populacao_estimada).alias('Receitas_pc')).join(ClassificaçõesMunicipio,on=(ReceitasAdicionais.municipio==ClassificaçõesMunicipio.Municipio)).join(Populacao,on=((ReceitasAdicionais.municipio==Populacao.municipio) |(ReceitasAdicionais.ano==Populacao.Ano))).where((ReceitasAdicionais.campo=='Provenientes da União')|(ReceitasAdicionais.campo == 'Provenientes dos Estados')| (ReceitasAdicionais.campo== "TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE") &(ReceitasAdicionais.estado == "Ceará"))
#Apuração= pd.DataFrame(dados.dicts())
Apuração = pd.read_csv("Tabela_apuração.csv")
Apuração_def = pd.DataFrame(Apuração['Receitas_realizadas_Bimestre'].values,index= time_serie(Apuração['ano']))

In [5]:
datetime.datetime.strptime(str(2019),"%Y")

datetime.datetime(2019, 1, 1, 0, 0)

In [6]:
# Importando dados de Receitas Adicionais

#data = ReceitasAdicionais.select(ReceitasAdicionais.municipio, ClassificaçõesMunicipio.Região, ClassificaçõesMunicipio.IDH,ReceitasAdicionais.codigo_Municipio, ReceitasAdicionais.estado, ReceitasAdicionais.ano, ReceitasAdicionais.campo, ReceitasAdicionais.Receitas_realizadas_Bimestre,(ReceitasAdicionais.Receitas_realizadas_Bimestre/Populacao.populacao_estimada).alias('Receitas_pc')).join(ClassificaçõesMunicipio,on=(ReceitasAdicionais.municipio == ClassificaçõesMunicipio.Municipio)).join(Populacao,on=((ReceitasAdicionais.municipio==Populacao.municipio)|(ReceitasAdicionais.ano == População.ano)).where((ReceitasAdicionais.campo=='Provenientes da União')|(ReceitasAdicionais.campo == 'Provenientes dos Estados')| (ReceitasAdicionais.campo== "TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II") &(ReceitasAdicionais.estado == "Ceará"))
#Adicional = pd.DataFrame(dados.dicts())
Adicional = pd.read_csv("adicional.csv")
Adicional_def = pd.DataFrame(Adicional['Receitas_realizadas_Bimestre'].values,index= time_serie(Adicional['ano']))
Adicional['Receitas_realizadas_Bimestre'] = Adicional_def.values

#  Deflacionar indicadores - Aplicar função de deflação

## 1. Receita Municipal total - Região

In [7]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Apuração['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Apuração['ano']):
            região = Apuração[(Apuração['Região']==Região) & (Apuração['ano']==ano)]
            numerador = sum(região[região['campo']=='RECEITA DE IMPOSTOS LÍQUIDA (I)']['Receitas_realizadas_Bimestre'])
            tabela[str(ano)].append(round(numerador/1000000,2))

In [8]:
pd.DataFrame(tabela).to_csv("1. Receita Municipal total - Região.csv")
pd.DataFrame(tabela)

,Região,2013,2014,2015,2016,2017,2018,2019
0,Acaraú,83.10,108.60,89.50,118.88,99.14,155.64,183.90
1,Aracati,87.33,108.64,140.65,146.09,183.30,199.97,232.65
2,Baturité,45.53,51.76,52.33,65.33,61.58,102.11,75.31
3,BrejoSanto,120.42,229.71,308.14,300.05,182.02,192.37,242.39
4,Camocim,49.73,53.60,54.55,70.23,62.39,98.25,96.42
5,Canidé,40.31,37.90,46.19,67.97,69.04,71.13,70.00
6,Cascavel,204.42,239.35,284.25,306.59,335.53,392.99,415.25
7,Caucaia,1207.10,1886.83,2186.63,1898.59,1749.15,1670.35,1840.36
8,Crateús,120.45,136.46,133.17,428.47,177.34,213.27,242.21
9,Crato,160.64,193.38,213.01,192.83,248.76,303.83,317.70
10,Fortaleza,8009.45,9676.49,10775.90,11219.64,12420.06,13626.65,14821.71
11,Icó,31.27,46.40,69.03,63.42,49.64,58.09,61.74
12,Iguatú,236.36,249.69,301.44,333.05,278.08,375.82,338.01
13,Itapipoca,145.13,140.42,135.30,185.15,164.63,219.14,252.55
14,JuazeiroNorte,52.21,78.02,65.35,77.31,116.60,109.58,121.32
15,LimoeirodoNorte,136.46,142.55,138.59,152.00,180.10,244.32,233.04
16,Maracanaú,429.39,544.72,598.35,597.09,659.21,785.34,922.91
17,Quixadá,148.96,153.23,185.82,215.97,206.63,258.55,245.63
18,Russas,75.53,90.29,115.65,101.79,122.33,136.77,143.54
19,Sobral,306.86,406.74,427.68,428.19,550.70,601.96,633.75
20,Tauá,61.57,61.56,81.39,86.92,78.48,86.08,90.99
21,Tianguá,64.20,91.35,96.41,131.06,130.32,169.26,151.84

# Repetidas - Caucaia e Sobral 
# Inexistente - Cariri e Farias Brito

## 2. Receita Municipal per capita - Região

In [9]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Apuração['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Apuração['ano']):
            região = Apuração[(Apuração['Região']==Região) & (Apuração['ano']==ano)]
            população = sum(região[região['campo']=='RECEITA DE IMPOSTOS LÍQUIDA (I)']['populacao_estimada'])
            numerador = sum(região[região['campo']=='RECEITA DE IMPOSTOS LÍQUIDA (I)']['Receitas_realizadas_Bimestre'])
            tabela[str(ano)].append(round(numerador/população,2))

In [10]:
pd.DataFrame(tabela).to_csv("2. Receita Municipal total per capita - Região.csv")
pd.DataFrame(tabela)

             Região    2013    2014    2015    2016    2017    2018    2019
0            Acaraú   46.92   61.33   50.54   67.13   55.98   87.89  103.85
1           Aracati  106.80  132.86  172.01  178.67  224.18  244.56  284.53
2          Baturité   57.34   65.19   65.90   82.27   77.55  128.58   94.84
3        BrejoSanto   74.54  142.18  190.73  185.73  116.66  119.07  150.03
4           Camocim   45.53   49.08   49.95   64.31   62.31   89.97   88.29
5            Canidé   44.93   42.25   51.49   75.78   76.96   79.30   78.04
6          Cascavel   45.52   53.29   63.29   68.27   74.71   87.51   92.46
7           Caucaia  266.19  416.09  482.20  418.68  385.73  368.35  405.84
8           Crateús   53.27   60.35   58.89  189.48   78.42   94.31  107.11
9             Crato   66.57   80.14   88.27   79.91  103.09  125.91  131.65
10        Fortaleza  410.59  496.05  552.41  575.15  636.69  698.54  759.81
11              Icó   52.84   78.43  116.67  107.19   83.89   98.17  104.35
12           Iguatú  104.75  110.66  133.59  147.60  129.38  166.56  179.63
13        Itapipoca   73.83   71.43   68.83   94.19   83.75  111.48  128.48
14    JuazeiroNorte   51.85   77.48   64.90   76.77  115.79  108.83  120.48
15  LimoeirodoNorte   88.09   92.02   89.46   98.13  116.26  157.72  150.44
16        Maracanaú   97.22  123.33  135.48  135.19  149.26  177.81  208.96
17          Quixadá   65.30   67.17   81.46   94.67   90.58  113.34  107.68
18           Russas   54.24   64.84   83.05   73.10   87.85   98.22  103.08
19           Sobral   70.72   93.74   98.57  101.68  126.92  138.73  146.06
20             Tauá   90.40   90.38  119.50  127.62  115.23  126.39  133.60
21          Tianguá   42.59   60.60   63.96   86.95   86.45  112.29  100.73

## 3. Percentual da receita liquida municipal (Capacidade)

In [11]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Apuração['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['Região']==Região) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=='RECEITA DE IMPOSTOS LÍQUIDA (I)']['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [12]:
pd.DataFrame(tabela).to_csv("3. Percentual da receita liquida municipal.csv")
pd.DataFrame(tabela)

,Região,2013,2014,2015,2016,2017,2018,2019
0,Acaraú,0.072247,0.086468,0.068082,0.081981,0.068999,0.095034,0.095877
1,Aracati,0.120425,0.131413,0.156279,0.141528,0.174345,0.176188,0.194097
2,Baturité,0.056829,0.061251,0.059721,0.066951,0.062249,0.092880,0.064525
3,BrejoSanto,0.080995,0.130521,0.161320,0.158313,0.110610,0.107117,0.117782
4,Camocim,0.067654,0.065692,0.062033,0.068537,0.068682,0.091972,0.082319
5,Canidé,0.062631,0.054984,0.061396,0.078222,0.081437,0.079740,0.072976
6,Cascavel,0.098158,0.107398,0.117678,0.113610,0.126210,0.135084,0.137977
7,Caucaia,0.340367,0.429421,0.440844,0.362406,0.332872,0.306354,0.301582
8,Crateús,0.060954,0.063573,0.058573,0.142946,0.068405,0.077878,0.082709
9,Crato,0.080621,0.087099,0.091932,0.081886,0.099174,0.116348,0.110882
10,Fortaleza,0.401183,0.425458,0.443065,0.435704,0.451800,0.456697,0.458038
11,Icó,0.049194,0.065749,0.090654,0.075646,0.063161,0.067154,0.068648
12,Iguatú,0.115653,0.113008,0.128788,0.126984,0.119954,0.132667,0.126620
13,Itapipoca,0.120464,0.109658,0.097404,0.116132,0.104896,0.127303,0.134321
14,JuazeiroNorte,0.068554,0.090867,0.073289,0.081139,0.123154,0.114721,0.107145
15,LimoeirodoNorte,0.100195,0.095871,0.089891,0.088262,0.103685,0.126902,0.109702
16,Maracanaú,0.109962,0.124068,0.133873,0.119048,0.128897,0.142109,0.154015
17,Quixadá,0.082894,0.079356,0.091310,0.094036,0.090354,0.107643,0.100307
18,Russas,0.076649,0.083947,0.100244,0.079666,0.096446,0.099108,0.102258
19,Sobral,0.079964,0.094540,0.093795,0.085852,0.104710,0.109411,0.106921
20,Tauá,0.127938,0.179376,0.143562,0.134870,0.123484,0.126478,0.132280
21,Tianguá,0.061334,0.077919,0.078763,0.091152,0.091895,0.112521,0.096260

### 4. Percentual da receita Liquida - IDH (Capacidade)

In [13]:
tabela={'IDH':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for IDH in np.unique(Apuração['IDH']):
        tabela['IDH'].append(IDH)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['IDH']==IDH) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=='RECEITA DE IMPOSTOS LÍQUIDA (I)']['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [14]:
pd.DataFrame(tabela).to_csv("4. Percentual da receita Liquida - IDH.csv")
pd.DataFrame(tabela)

     IDH      2013      2014      2015      2016      2017      2018      2019
0   Alto  0.185502  0.216039  0.225534  0.232441  0.242612  0.265829  0.278702
1  Baixo  0.054040  0.052726  0.051307  0.048832  0.062994  0.069288  0.057487
2  Medio  0.246220  0.273232  0.286439  0.273376  0.280789  0.286153  0.286735

### 11. Receitas liquida municipal  - Porte (Capacidade)

In [15]:
tabela={'Porte':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Porte in np.unique(Apuração['Porte']):
        tabela['Porte'].append(Porte)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['Porte']==Porte) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=='RECEITA DE IMPOSTOS LÍQUIDA (I)']['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [16]:
pd.DataFrame(tabela).to_csv("11. Receitas liquida municipal - Porte.csv")
pd.DataFrame(tabela)

,Porte,2013,2014,2015,2016,2017,2018,2019
0,Até 5.000 hab.,0.069883,0.056483,0.051556,0.097351,0.086271,0.089803,0.093498
1,De 10.001 a 20.000 hab.,0.048922,0.048144,0.052042,0.048734,0.059334,0.069255,0.061617
2,De 100.001 a 500.000 hab.,0.165788,0.183382,0.195241,0.183304,0.195927,0.202862,0.212213
3,De 20.001 a 50.000 hab.,0.147024,0.191062,0.204552,0.178947,0.162903,0.164316,0.161673
4,De 5.001 a 10.000 hab.,0.052583,0.069016,0.066749,0.058800,0.049554,0.068453,0.072302
5,De 50.001 a 100.000 hab.,0.124822,0.140084,0.148850,0.172230,0.163107,0.173521,0.179412
6,Mais de 500.000 hab.,0.410578,0.434424,0.451496,0.441669,0.459668,0.464917,0.466431

### 5. Receita total per capita - IDH

In [17]:
tabela={'IDH':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for IDH in np.unique(Apuração['IDH']):
        tabela['IDH'].append(IDH)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['IDH']==IDH) & (Apuração['ano']==ano)]
                população = sum(região[região['campo']=='RECEITA DE IMPOSTOS LÍQUIDA (I)']['populacao_estimada'])
                numerador = sum(região[região['campo']=='TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/população)
            except:
                tabela[str(ano)].append(0)

In [18]:
pd.DataFrame(tabela).to_csv("Receita total per capita.csv")
pd.DataFrame(tabela)

,IDH,2013,2014,2015,2016,2017,2018,2019
0,Alto,884.182772,994.542045,1064.894686,1174.247277,1262.637809,1381.293804,1505.256076
1,Baixo,817.117370,902.126800,958.652853,1080.999685,1060.539234,1126.465593,1226.235608
2,Medio,858.383490,965.557660,1033.886213,1125.491364,1145.627290,1234.877145,1338.289522

### 12. Receita total per capita - porte

In [19]:
tabela={'Porte':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Porte in np.unique(Apuração['Porte']):
        tabela['Porte'].append(Porte)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['Porte']==Porte) & (Apuração['ano']==ano)]
                população = sum(região[região['campo']=='RECEITA DE IMPOSTOS LÍQUIDA (I)']['populacao_estimada'])
                numerador = sum(região[região['campo']=='TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/população)
            except:
                tabela[str(ano)].append(0)

In [20]:
pd.DataFrame(tabela).to_csv(" Receita total per capita.csv")
pd.DataFrame(tabela)

,Porte,2013,2014,2015,2016,2017,2018,2019
0,Até 5.000 hab.,2262.803663,2462.530052,2663.846594,2958.672009,2827.761878,2889.730967,3312.020607
1,De 10.001 a 20.000 hab.,996.038497,1087.949824,1167.974002,1285.758132,1288.961974,1351.606347,1478.508282
2,De 100.001 a 500.000 hab.,763.988779,850.849656,901.911185,965.567502,984.506082,1078.304495,1170.635551
3,De 20.001 a 50.000 hab.,824.480106,947.672899,1021.733982,1140.575997,1121.845842,1188.182475,1306.272753
4,De 5.001 a 10.000 hab.,1382.610399,1548.492433,1582.669966,1685.283848,1657.107233,1832.594832,1937.679457
5,De 50.001 a 100.000 hab.,601.944973,652.767510,709.516687,849.139112,824.745336,902.383954,954.504256
6,Mais de 500.000 hab.,1010.082081,1148.303394,1220.815899,1276.321409,1365.852254,1477.107757,1595.655731

### 6. Transferências da União e Estado 
#### 6.1 Transferências da União

In [21]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Apuração['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['Região']==Região) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=="Cota-Parte FPM"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte ITR"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Desoneração ICMS (LC 87/96)"]['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [22]:
pd.DataFrame(tabela).to_csv("6.1 Transferências da União.csv")
pd.DataFrame(tabela)

,Região,2013,2014,2015,2016,2017,2018,2019
0,Acaraú,0.704810,0.691401,0.709381,0.715733,0.694924,0.665571,0.609708
1,Aracati,0.542265,0.534959,0.519368,0.525416,0.468218,0.465444,0.467969
2,Baturité,0.736430,0.743825,0.752429,0.751298,0.730083,0.703481,0.697482
3,BrejoSanto,0.703053,0.650724,0.635723,0.670801,0.682765,0.651634,0.656036
4,Camocim,0.741434,0.738763,0.731536,0.721270,0.699749,0.683592,0.679008
5,Canidé,0.784941,0.780621,0.779761,0.771885,0.742660,0.741908,0.723717
6,Cascavel,0.560728,0.572212,0.568309,0.580021,0.553066,0.544939,0.535269
7,Caucaia,0.398605,0.344951,0.321882,0.349620,0.323071,0.332808,0.319629
8,Crateús,0.745551,0.740269,0.728434,0.669513,0.716750,0.697751,0.703609
9,Crato,0.645713,0.623809,0.636132,0.682742,0.630873,0.623738,0.616077
10,Fortaleza,0.228945,0.222260,0.217733,0.236434,0.213872,0.212057,0.210796
11,Icó,0.732802,0.713058,0.699071,0.728516,0.743564,0.723070,0.720246
12,Iguatú,0.643086,0.642041,0.641044,0.651694,0.652540,0.635297,0.620180
13,Itapipoca,0.685606,0.702912,0.692011,0.679660,0.647396,0.622030,0.617680
14,JuazeiroNorte,0.690851,0.674128,0.690808,0.726664,0.648879,0.633387,0.650480
15,LimoeirodoNorte,0.660383,0.653647,0.662315,0.669247,0.629277,0.599211,0.609797
16,Maracanaú,0.445786,0.423469,0.403827,0.440048,0.408868,0.404280,0.403583
17,Quixadá,0.679483,0.687021,0.696855,0.705898,0.678971,0.667875,0.657460
18,Russas,0.651041,0.649708,0.646610,0.671475,0.620434,0.615013,0.615446
19,Sobral,0.591595,0.593222,0.587376,0.606376,0.574588,0.584011,0.577422
20,Tauá,0.710726,0.535656,0.681222,0.704535,0.680500,0.677129,0.679094
21,Tianguá,0.698843,0.709730,0.715065,0.704521,0.667340,0.656701,0.669367

### 6.2 Transferências do Estado

In [23]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Apuração['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['Região']==Região) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=="Cota-Parte ICMS"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte IPI-Exportação"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte IPVA"]['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

### 13. Transferências da União e Estado 
#### 13.1 Transferências da União

In [24]:
tabela={'Porte':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Porte in np.unique(Apuração['Porte']):
        tabela['Porte'].append(Porte)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['Porte']==Porte) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=="Cota-Parte FPM"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte ITR"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Desoneração ICMS (LC 87/96)"]['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [25]:
pd.DataFrame(tabela).to_csv("13.1 Transferências da União - Porte.csv")
pd.DataFrame(tabela)

,Porte,2013,2014,2015,2016,2017,2018,2019
0,Até 5.000 hab.,0.678880,0.670582,0.657049,0.689954,0.661556,0.598240,0.598124
1,De 10.001 a 20.000 hab.,0.708995,0.714726,0.707115,0.730041,0.692660,0.691190,0.682796
2,De 100.001 a 500.000 hab.,0.408622,0.391245,0.388942,0.411603,0.381217,0.380296,0.379055
3,De 20.001 a 50.000 hab.,0.647874,0.611495,0.597566,0.612397,0.590243,0.579802,0.568067
4,De 5.001 a 10.000 hab.,0.605570,0.587418,0.606506,0.633330,0.610720,0.598168,0.582783
5,De 50.001 a 100.000 hab.,0.577018,0.561840,0.557199,0.550623,0.530128,0.517632,0.505816
6,Mais de 500.000 hab.,0.221005,0.214769,0.211257,0.231966,0.209570,0.209281,0.208762

#### 6.2 Transferências do Estado

In [26]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Apuração['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['Região']==Região) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=="Cota-Parte ICMS"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte IPI-Exportação"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte IPVA"]['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [27]:
pd.DataFrame(tabela).to_csv("6.2Transferências do Estado.csv ")
pd.DataFrame(tabela)

,Região,2013,2014,2015,2016,2017,2018,2019
0,Acaraú,0.222155,0.221436,0.221860,0.201693,0.235462,0.239395,0.294415
1,Aracati,0.336099,0.332535,0.323333,0.332054,0.356449,0.358368,0.337935
2,Baturité,0.205994,0.194287,0.187249,0.181192,0.207096,0.203638,0.237993
3,BrejoSanto,0.215192,0.218047,0.202330,0.170403,0.206093,0.241248,0.226182
4,Camocim,0.190238,0.194913,0.205787,0.209567,0.230940,0.224436,0.238673
5,Canidé,0.151856,0.163810,0.158365,0.149459,0.175438,0.178352,0.203307
6,Cascavel,0.339881,0.319331,0.313000,0.305464,0.319858,0.319977,0.326755
7,Caucaia,0.260101,0.224895,0.236472,0.287110,0.343144,0.360838,0.378789
8,Crateús,0.192747,0.195512,0.212314,0.187039,0.214279,0.224370,0.213682
9,Crato,0.272709,0.288191,0.271102,0.234687,0.269243,0.259913,0.273040
10,Fortaleza,0.368687,0.351254,0.338255,0.327003,0.333529,0.331246,0.331166
11,Icó,0.217228,0.220481,0.209625,0.195259,0.192753,0.209775,0.211105
12,Iguatú,0.240454,0.244209,0.229504,0.220720,0.226945,0.232037,0.253200
13,Itapipoca,0.193273,0.186840,0.209946,0.203615,0.247075,0.250667,0.247999
14,JuazeiroNorte,0.239756,0.234241,0.235175,0.191648,0.227366,0.251893,0.242375
15,LimoeirodoNorte,0.238609,0.249706,0.247063,0.241802,0.266349,0.273887,0.280502
16,Maracanaú,0.442647,0.450958,0.460817,0.439564,0.460938,0.453612,0.442403
17,Quixadá,0.236809,0.232902,0.211215,0.199510,0.230070,0.224481,0.242233
18,Russas,0.271369,0.265511,0.252384,0.248063,0.282374,0.285880,0.282296
19,Sobral,0.327274,0.311222,0.317833,0.306853,0.319823,0.306578,0.315657
20,Tauá,0.160821,0.284129,0.174707,0.160155,0.195481,0.196392,0.188625
21,Tianguá,0.239025,0.211724,0.205585,0.203783,0.240188,0.230778,0.234373

#### 13.2 Transferências do Estado

In [28]:
tabela={'Porte':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Porte in np.unique(Apuração['Porte']):
        tabela['Porte'].append(Porte)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['Porte']==Porte) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=="Cota-Parte ICMS"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte IPI-Exportação"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte IPVA"]['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [29]:
pd.DataFrame(tabela).to_csv("13.2 Transferências do Estado.csv")
pd.DataFrame(tabela)

,Porte,2013,2014,2015,2016,2017,2018,2019
0,Até 5.000 hab.,0.250322,0.271998,0.290437,0.212024,0.251454,0.311956,0.308377
1,De 10.001 a 20.000 hab.,0.241197,0.236347,0.240073,0.220557,0.247307,0.239556,0.255587
2,De 100.001 a 500.000 hab.,0.424104,0.424023,0.414544,0.403913,0.421730,0.416842,0.408732
3,De 20.001 a 50.000 hab.,0.204373,0.196806,0.197254,0.208048,0.246207,0.255882,0.270259
4,De 5.001 a 10.000 hab.,0.340581,0.342407,0.325667,0.306871,0.338752,0.333379,0.344915
5,De 50.001 a 100.000 hab.,0.297129,0.297126,0.293046,0.276346,0.305953,0.308847,0.314772
6,Mais de 500.000 hab.,0.367246,0.349794,0.336317,0.325522,0.329983,0.325802,0.324807

### 7. Transferências da União e Estado - IDH
#### 7.1 Transferências da União

In [30]:
tabela={'IDH':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for IDH in np.unique(Apuração['IDH']):
        tabela['IDH'].append(IDH)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['IDH']==IDH) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=="Cota-Parte FPM"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte ITR"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Desoneração ICMS (LC 87/96)"]['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [31]:
pd.DataFrame(tabela).to_csv("7.1 Transferências da União - IDH.csv")
pd.DataFrame(tabela)

     IDH      2013      2014      2015      2016      2017      2018      2019
0   Alto  0.400918  0.384343  0.378674  0.391318  0.367941  0.353126  0.342462
1  Baixo  0.744425  0.743463  0.740866  0.755205  0.724108  0.713903  0.724156
2  Medio  0.434120  0.417068  0.412252  0.433701  0.403656  0.399030  0.393440

#### 7.2 Transferências da Estado

In [32]:
tabela={'IDH':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for IDH in np.unique(Apuração['IDH']):
        tabela['IDH'].append(IDH)
        for ano in np.unique(Apuração['ano']):
            try:
                região = Apuração[(Apuração['IDH']==IDH) & (Apuração['ano']==ano)]
                numerador = sum(região[região['campo']=="Cota-Parte ICMS"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte IPI-Exportação"]['Receitas_realizadas_Bimestre']) + sum(região[região['campo']=="Cota-Parte IPVA"]['Receitas_realizadas_Bimestre'])
                denominador = sum(região[região['campo']== 'TOTAL DAS RECEITAS PARA APURAÇÃO DA APLICAÇÃO EM AÇÕES E SERVIÇOS PÚBLICOS DE SAÚDE (III) = I + II']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [33]:
pd.DataFrame(tabela).to_csv("7.2 Transferências da Estado.csv")
pd.DataFrame(tabela)

     IDH      2013      2014      2015      2016      2017      2018      2019
0   Alto  0.412153  0.398380  0.394595  0.375161  0.388429  0.381045  0.378834
1  Baixo  0.200812  0.203139  0.207158  0.195371  0.212313  0.216808  0.218357
2  Medio  0.318582  0.308750  0.300418  0.292109  0.314754  0.314817  0.319825

### 8. Receita adicional total

In [34]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Adicional['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['Região']==Região) & (Adicional['ano']==ano)]
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(round(denominador/1000000,2))
            except:
                tabela[str(ano)].append(0)

In [35]:
pd.DataFrame(tabela).to_csv("8. Receita adicional total.csv")
pd.DataFrame(tabela)

,Região,2013,2014,2015,2016,2017,2018,2019
0,Acaraú,356.04,315.09,288.18,395.53,331.23,321.59,465.40
1,Aracati,272.19,193.11,184.37,241.17,235.11,295.89,332.05
2,Baturité,278.41,190.94,231.35,229.96,228.55,249.37,282.79
3,BrejoSanto,651.42,479.63,416.21,515.39,492.42,567.86,608.34
4,Camocim,350.34,306.11,235.59,352.56,259.41,281.17,344.49
5,Canidé,222.44,152.86,167.21,165.08,172.66,221.61,234.23
6,Cascavel,496.90,476.35,546.08,635.23,581.73,757.02,738.58
7,Caucaia,1264.16,753.00,843.17,901.36,934.36,1414.99,1182.80
8,Crateús,456.15,585.05,544.05,567.11,618.55,786.72,752.71
9,Crato,723.73,706.06,653.03,842.46,869.02,1049.03,1106.81
10,Fortaleza,5306.29,6309.56,6401.66,6953.47,7226.28,7794.05,7946.45
11,Icó,172.32,129.67,133.49,167.00,181.51,199.89,181.12
12,Iguatú,603.08,611.71,610.46,692.32,662.68,758.83,744.40
13,Itapipoca,379.05,436.05,454.74,483.02,593.46,644.54,566.39
14,JuazeiroNorte,995.14,635.83,696.99,579.08,788.23,756.63,761.33
15,LimoeirodoNorte,346.13,390.26,340.35,409.60,435.43,502.11,558.73
16,Maracanaú,987.35,1046.25,1124.98,1283.77,1238.20,1490.66,1503.64
17,Quixadá,555.33,688.63,614.13,655.26,713.19,932.19,893.29
18,Russas,284.59,351.13,318.75,395.00,413.80,536.14,535.15
19,Sobral,1587.24,1798.72,1726.17,1837.85,1870.94,2159.69,2170.98
20,Tauá,189.85,266.13,218.84,303.29,209.79,332.20,328.97
21,Tianguá,340.96,352.06,398.56,458.49,385.49,612.14,519.87

### 9. Receita adicional total - per capita

##### Região

In [36]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Adicional['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['Região']==Região) & (Adicional['ano']==ano)]
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                populacao =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['populacao_estimada'])
                tabela[str(ano)].append(round(denominador/populacao,2))
            except:
                tabela[str(ano)].append(0)

In [37]:
pd.DataFrame(tabela).to_csv("9. Receita adicional total - per capita")

### Idh

In [38]:
tabela={'IDH':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for IDH in np.unique(Adicional['IDH']):
        tabela['IDH'].append(IDH)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['IDH']==IDH) & (Adicional['ano']==ano)]
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                populacao =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['populacao_estimada'])
                tabela[str(ano)].append(round(denominador/populacao,2))
            except:
                tabela[str(ano)].append(0)

In [39]:
pd.DataFrame(tabela).to_csv("9.1 Receita adicional total - per capita (IDH)")

### Porte

In [40]:
tabela={'Porte':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Porte in np.unique(Adicional['Porte']):
        tabela['Porte'].append(Porte)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['Porte']==Porte) & (Adicional['ano']==ano)]
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                populacao =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['populacao_estimada'])
                tabela[str(ano)].append(round(denominador/populacao,2))
            except:
                tabela[str(ano)].append(0)

In [41]:
pd.DataFrame(tabela).to_csv("9.2 Receita adicional total - per capita (Porte)")

### 10. Receita adicional percentual
#### União

In [42]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Adicional['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['Região']==Região) & (Adicional['ano']==ano)]
                numerador = sum(região[região['campo']=='Provenientes da União']['Receitas_realizadas_Bimestre']) 
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [43]:
pd.DataFrame(tabela).to_csv("10.1 Receita adicional percentual - União.csv")
pd.DataFrame(tabela)

,Região,2013,2014,2015,2016,2017,2018,2019
0,Acaraú,0.993267,0.984561,0.980411,0.836597,0.975663,0.986899,0.930458
1,Aracati,0.852377,0.871840,0.859647,0.886650,0.856186,0.976095,0.902704
2,Baturité,0.921461,0.945883,0.942253,0.978070,0.988431,0.978128,0.956503
3,BrejoSanto,0.940669,0.901553,0.982538,0.991352,0.985470,0.990361,0.992613
4,Camocim,0.986128,0.818790,0.886760,0.880226,0.907130,0.999607,0.926182
5,Canidé,0.946696,0.970412,0.932598,0.996034,0.970716,0.988739,0.937232
6,Cascavel,0.989672,0.870806,0.951517,0.944057,0.915462,0.943098,0.957149
7,Caucaia,0.916354,0.912188,0.896011,0.907930,0.929775,0.807234,0.964791
8,Crateús,0.990468,0.886030,0.894028,0.972468,0.911356,0.911866,0.937507
9,Crato,0.944696,0.878921,0.983874,0.860621,0.885939,0.878150,0.920963
10,Fortaleza,0.963240,0.924665,0.913901,0.902206,0.904356,0.882900,0.920354
11,Icó,0.990652,0.971741,0.946216,0.977454,0.985794,0.989939,0.995364
12,Iguatú,0.985529,0.889966,0.856291,0.928519,0.918877,0.980920,0.995274
13,Itapipoca,0.963360,0.902209,0.977229,0.922746,0.916666,0.925133,0.919781
14,JuazeiroNorte,0.991132,0.980308,0.942942,0.982134,0.863791,0.989997,0.998722
15,LimoeirodoNorte,0.921051,0.884459,0.955281,0.950840,0.893834,0.875832,0.907612
16,Maracanaú,0.958846,0.904085,0.918055,0.937320,0.927588,0.932276,0.944620
17,Quixadá,0.924000,0.819300,0.888271,0.957279,0.891012,0.842902,0.844977
18,Russas,0.992389,0.872638,0.968780,0.993373,0.909719,0.978537,0.981426
19,Sobral,0.958526,0.885215,0.922261,0.927055,0.930713,0.903842,0.921468
20,Tauá,0.948415,0.650153,0.998943,0.810439,1.000000,0.870621,0.916143
21,Tianguá,0.967907,0.930791,0.873729,0.886370,0.973728,0.785584,0.927850

#### Estado

In [44]:
tabela={'Região':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Região in np.unique(Adicional['Região']):
        tabela['Região'].append(Região)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['Região']==Região) & (Adicional['ano']==ano)]
                numerador = sum(região[região['campo']=='Provenientes dos Estados']['Receitas_realizadas_Bimestre']) 
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [45]:
pd.DataFrame(tabela).to_csv("10.2 Receita adicional percentual - Estado.csv")
pd.DataFrame(tabela)

,Região,2013,2014,2015,2016,2017,2018,2019
0,Acaraú,0.000377,0.010721,0.004060,0.000960,0.020925,0.011448,0.068536
1,Aracati,0.143520,0.119934,0.125977,0.105831,0.138101,0.019541,0.096249
2,Baturité,0.070979,0.048858,0.048763,0.013922,0.008366,0.017731,0.039704
3,BrejoSanto,0.051425,0.085495,0.002008,0.004711,0.006783,0.004980,0.005736
4,Camocim,0.004260,0.096307,0.070287,0.114130,0.065980,0.000348,0.007444
5,Canidé,0.023046,0.025532,0.032418,0.000000,0.022484,0.008734,0.060867
6,Cascavel,0.004546,0.066480,0.040764,0.048644,0.077608,0.055146,0.040602
7,Caucaia,0.081003,0.082822,0.085817,0.078560,0.062955,0.006705,0.026761
8,Crateús,0.002876,0.102308,0.083280,0.019093,0.085205,0.086541,0.056508
9,Crato,0.050036,0.114842,0.007627,0.133666,0.107981,0.118913,0.075785
10,Fortaleza,0.027984,0.068736,0.077787,0.089192,0.090254,0.112439,0.074681
11,Icó,0.000020,0.017619,0.043029,0.018322,0.008259,0.008850,0.002461
12,Iguatú,0.006091,0.099006,0.076529,0.065921,0.076993,0.017382,0.003846
13,Itapipoca,0.009796,0.086075,0.005049,0.064516,0.079296,0.069883,0.078562
14,JuazeiroNorte,0.001438,0.000000,0.004780,0.000907,0.131183,0.009701,0.000940
15,LimoeirodoNorte,0.072228,0.101467,0.032052,0.043613,0.099665,0.098529,0.092045
16,Maracanaú,0.037127,0.084063,0.061166,0.053134,0.063989,0.064854,0.040597
17,Quixadá,0.069147,0.122690,0.103515,0.039263,0.107957,0.085134,0.077215
18,Russas,0.003973,0.118066,0.000792,0.001182,0.085587,0.018355,0.016273
19,Sobral,0.034870,0.088906,0.066776,0.063825,0.060893,0.060619,0.058397
20,Tauá,0.027850,0.287035,0.000898,0.186024,0.000000,0.128652,0.083711
21,Tianguá,0.022174,0.003832,0.093677,0.106625,0.010363,0.062557,0.069831

### 16. Receita adicional percentual IDH
#### 16.1 União

In [46]:
tabela={'IDH':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for IDH in np.unique(Adicional['IDH']):
        tabela['IDH'].append(IDH)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['IDH']==IDH) & (Adicional['ano']==ano)]
                numerador = sum(região[região['campo']=='Provenientes da União']['Receitas_realizadas_Bimestre']) 
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [47]:
pd.DataFrame(tabela).to_csv("16.Receita adicional percentual IDH -União.csv")
pd.DataFrame(tabela)

     IDH      2013      2014      2015      2016      2017      2018      2019
0   Alto  0.978492  0.888581  0.929945  0.890940  0.903972  0.892485  0.897246
1  Baixo  0.977804  0.961170  0.943650  0.983005  0.975972  0.888550  0.971106
2  Medio  0.953673  0.898857  0.918794  0.915544  0.910942  0.904376  0.932893

#### 10.1 Estado

In [48]:
tabela={'IDH':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for IDH in np.unique(Adicional['IDH']):
        tabela['IDH'].append(IDH)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['IDH']==IDH) & (Adicional['ano']==ano)]
                numerador = sum(região[região['campo']=='Provenientes dos Estados']['Receitas_realizadas_Bimestre']) 
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [49]:
pd.DataFrame(tabela).to_csv("10.2.Receita adicional percentual IDH -Estado.csv")
pd.DataFrame(tabela)

     IDH      2013      2014      2015      2016      2017      2018      2019
0   Alto  0.020341  0.105997  0.060086  0.098771  0.086772  0.103417  0.097794
1  Baixo  0.010298  0.027377  0.013743  0.011583  0.019776  0.035111  0.013717
2  Medio  0.038067  0.081774  0.066415  0.072190  0.083045  0.073967  0.057145

### 15. Receita adicional percentual Porte
#### 15.1 União

In [50]:
tabela={'Porte':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Porte in np.unique(Adicional['Porte']):
        tabela['Porte'].append(Porte)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['Porte']==Porte) & (Adicional['ano']==ano)]
                numerador = sum(região[região['campo']=='Provenientes da União']['Receitas_realizadas_Bimestre']) 
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [51]:
pd.DataFrame(tabela).to_csv("15. Receita adicional percentual Porte.csv")
pd.DataFrame(tabela)

,Porte,2013,2014,2015,2016,2017,2018,2019
0,Até 5.000 hab.,0.981448,0.966595,0.941605,0.956192,0.995859,0.925939,0.974816
1,De 10.001 a 20.000 hab.,0.944120,0.938430,0.958674,0.971957,0.966970,0.895010,0.966605
2,De 100.001 a 500.000 hab.,0.949332,0.880870,0.901205,0.886544,0.897017,0.875011,0.936530
3,De 20.001 a 50.000 hab.,0.963446,0.929138,0.946847,0.954331,0.962608,0.945999,0.951837
4,De 5.001 a 10.000 hab.,0.980449,0.947102,0.965560,0.975271,0.975281,0.925414,0.990926
5,De 50.001 a 100.000 hab.,0.962477,0.844583,0.915313,0.924637,0.885069,0.926439,0.910534
6,Mais de 500.000 hab.,0.962064,0.921761,0.914370,0.898905,0.901908,0.882780,0.919493

#### 15.2 Estado

In [52]:
tabela={'Porte':[],'2013':[],'2014':[],'2015':[],'2016':[],'2017':[],'2018':[],'2019':[]}
for Porte in np.unique(Adicional['Porte']):
        tabela['Porte'].append(Porte)
        for ano in np.unique(Adicional['ano']):
            try:
                região = Adicional[(Adicional['Porte']==Porte) & (Adicional['ano']==ano)]
                numerador = sum(região[região['campo']=='Provenientes dos Estados']['Receitas_realizadas_Bimestre']) 
                denominador =  sum(região[região['campo']=='TOTAL RECEITAS ADICIONAIS PARA FINANCIAMENTO DA SAÚDE']['Receitas_realizadas_Bimestre'])
                tabela[str(ano)].append(numerador/denominador)
            except:
                tabela[str(ano)].append(0)

In [53]:
pd.DataFrame(tabela).to_csv("15.1 Receita adicional percentual Porte - Estado.csv")
pd.DataFrame(tabela)

,Porte,2013,2014,2015,2016,2017,2018,2019
0,Até 5.000 hab.,0.011048,0.025777,0.049259,0.033765,0.000000,0.071880,0.019942
1,De 10.001 a 20.000 hab.,0.038567,0.040953,0.025183,0.022080,0.026067,0.032895,0.019649
2,De 100.001 a 500.000 hab.,0.048641,0.114572,0.072925,0.103325,0.096375,0.064749,0.060415
3,De 20.001 a 50.000 hab.,0.027542,0.041521,0.027392,0.020840,0.030044,0.052147,0.035326
4,De 5.001 a 10.000 hab.,0.013929,0.042875,0.013451,0.018006,0.018259,0.028181,0.006700
5,De 50.001 a 100.000 hab.,0.030446,0.116606,0.070958,0.066629,0.107858,0.056475,0.067974
6,Mais de 500.000 hab.,0.029109,0.071745,0.077391,0.092815,0.093348,0.112554,0.075331